apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dvn-workshop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kenerry-serain/dvn-workshop-out-dia-2-gitops
    targetRevision: HEAD
    path: dvn-workshop-kubernetes/.
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true